# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def spectrum_probability_grid(index, secondary_product, data):
    offset = secondary_product["spectrum_probability_grid_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def spectrum_probability_grid_all(secondary_product, data):
    start = secondary_product["spectrum_probability_grid_offset"]
    size = secondary_product["spectrum_probability_grid_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def spectrum_probability_grid_last(secondary_product, data):
    start = secondary_product["spectrum_probability_grid_offset"]
    size = secondary_product["spectrum_probability_grid_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def spectrum_probability_grid_chunk(start, length, secondary_product, data):
    start += secondary_product["spectrum_probability_grid_offset"]
    end = start + length
    return array_result(data[start:end])


@array_return(nb.types.float64)
def spectrum_probability_vector(index_1, secondary_product, data):
    offset = secondary_product["spectrum_probability_offset"]
    stride = secondary_product["N_spectrum"]
    start = offset + index_1 * stride
    end = start + stride
    return array_result(data[start:end])


@njit
def spectrum_probability(index_1, index_2, secondary_product, data):
    offset = secondary_product["spectrum_probability_offset"]
    stride = secondary_product["N_spectrum"]
    return data[offset + index_1 * stride + index_2]


@array_return(nb.types.float64)
def spectrum_probability_chunk(start, length, secondary_product, data):
    start += secondary_product["spectrum_probability_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def energy_spectrum_IDs(index, secondary_product, data):
    offset = secondary_product["energy_spectrum_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def energy_spectrum_IDs_all(secondary_product, data):
    start = secondary_product["energy_spectrum_IDs_offset"]
    size = secondary_product["N_energy_spectrum"]
    end = start + size
    return array_result(data[start:end])


@njit
def energy_spectrum_IDs_last(secondary_product, data):
    start = secondary_product["energy_spectrum_IDs_offset"]
    size = secondary_product["N_energy_spectrum"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def energy_spectrum_IDs_chunk(start, length, secondary_product, data):
    start += secondary_product["energy_spectrum_IDs_offset"]
    end = start + length
    return array_result(data[start:end])
