# The following is automatically generated by code_factory.py

from numba import njit


@njit
def xs(index, neutron_reaction, data, value):
    offset = neutron_reaction["xs_offset"]
    data[offset + index] = value


@njit
def xs_all(neutron_reaction, data, value):
    start = neutron_reaction["xs_offset"]
    size = neutron_reaction["xs_length"]
    end = start + size
    data[start:end] = value


@njit
def xs_last(neutron_reaction, data, value):
    start = neutron_reaction["xs_offset"]
    size = neutron_reaction["xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def xs_chunk(start, length, neutron_reaction, data, value):
    start += neutron_reaction["xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def secondary_product_IDs(index, neutron_reaction, data, value):
    offset = neutron_reaction["secondary_product_IDs_offset"]
    data[offset + index] = value


@njit
def secondary_product_IDs_all(neutron_reaction, data, value):
    start = neutron_reaction["secondary_product_IDs_offset"]
    size = neutron_reaction["N_secondary_product"]
    end = start + size
    data[start:end] = value


@njit
def secondary_product_IDs_last(neutron_reaction, data, value):
    start = neutron_reaction["secondary_product_IDs_offset"]
    size = neutron_reaction["N_secondary_product"]
    end = start + size
    data[end - 1] = value


@njit
def secondary_product_IDs_chunk(start, length, neutron_reaction, data, value):
    start += neutron_reaction["secondary_product_IDs_offset"]
    end = start + length
    data[start:end] = value
