# The following is automatically generated by code_factory.py

from numba import njit


@njit
def spectrum_probability_grid(index, secondary_product, data, value):
    offset = secondary_product["spectrum_probability_grid_offset"]
    data[offset + index] = value


@njit
def spectrum_probability_grid_all(secondary_product, data, value):
    start = secondary_product["spectrum_probability_grid_offset"]
    size = secondary_product["spectrum_probability_grid_length"]
    end = start + size
    data[start:end] = value


@njit
def spectrum_probability_grid_last(secondary_product, data, value):
    start = secondary_product["spectrum_probability_grid_offset"]
    size = secondary_product["spectrum_probability_grid_length"]
    end = start + size
    data[end - 1] = value


@njit
def spectrum_probability_grid_chunk(start, length, secondary_product, data, value):
    start += secondary_product["spectrum_probability_grid_offset"]
    end = start + length
    data[start:end] = value


@njit
def spectrum_probability_vector(index_1, secondary_product, data, value):
    offset = secondary_product["spectrum_probability_offset"]
    stride = secondary_product["N_spectrum"]
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] = value


@njit
def spectrum_probability(index_1, index_2, secondary_product, data, value):
    offset = secondary_product["spectrum_probability_offset"]
    stride = secondary_product["N_spectrum"]
    data[offset + index_1 * stride + index_2] = value


@njit
def spectrum_probability_chunk(start, length, secondary_product, data, value):
    start += secondary_product["spectrum_probability_offset"]
    end = start + length
    data[start:end] = value


@njit
def energy_spectrum_IDs(index, secondary_product, data, value):
    offset = secondary_product["energy_spectrum_IDs_offset"]
    data[offset + index] = value


@njit
def energy_spectrum_IDs_all(secondary_product, data, value):
    start = secondary_product["energy_spectrum_IDs_offset"]
    size = secondary_product["N_energy_spectrum"]
    end = start + size
    data[start:end] = value


@njit
def energy_spectrum_IDs_last(secondary_product, data, value):
    start = secondary_product["energy_spectrum_IDs_offset"]
    size = secondary_product["N_energy_spectrum"]
    end = start + size
    data[end - 1] = value


@njit
def energy_spectrum_IDs_chunk(start, length, secondary_product, data, value):
    start += secondary_product["energy_spectrum_IDs_offset"]
    end = start + length
    data[start:end] = value
